### ISSUE TITLE
Integrate ElasticSearch results from MP in the RS

### ISSUE THREAD

**Issue by wujuu** [cyfronet-fid/recommender-system#144]
We are using the Mongo FTS engine, to narrow down the search space in our Recommendation systems. This engine is flawed and not as exhaustive as the FTS engine (elasticsearch) used in Marketplace. 

Ideally, the search spaces in Recommender System and Marketplace are identical

**Comment by Michal-Kolomanski** [comment]
We've determined that Marketplace will provide us with a list of services IDs that ElasticSearch returned to him directly. Our recommender does not need to query elastic or establish its own instance. However, we need to properly handle these ids and introduce quite a number of changes in our StateEncoder.
