### ISSUE TITLE
Address OpenAIGym's way of initial exploration

### ISSUE THREAD

**Issue by wujuu** [cyfronet-fid/recommender-system#194]
![Screenshot from 2021-10-05 14-34-25](https://user-images.githubusercontent.com/30239467/136023321-bfd5db2d-404d-49a7-bea8-b8ca56e84f2f.png)

**Comment by Michal-Kolomanski** [comment]
Are we still interested in that? @JanKapala @wujuu

**Comment by Michal-Kolomanski** [comment]
It can be relevant in the future
