### ISSUE TITLE
Refactor methods in the AEDataPreparationStep

### ISSUE THREAD

**Issue by wujuu** [cyfronet-fid/recommender-system#253]
There are a lot of deprecated methods in the AEDataPreparation step, as well as methods which can be easiy refactored into one (`user_and_service_to_tensors` and `users_and_services_to_tensors` for example). 

Add new module for helper funtions if needed.

**Comment by Michal-Kolomanski** [comment]
Done in [#274] Autoencoders unit and integration tests for each pipeline step #277
