### ISSUE TITLE
Add `show_plots` flag to training.py

### ISSUE THREAD

**Issue by wujuu** [cyfronet-fid/recommender-system#29]
There are unnecessary plots printed when running tests of the pre-agent training. We should add a flag to the class and disable plotting during testing

**Comment by JanKapala** [comment]
Maybe I will globally disable plotting in tests - it would be better than flag that the only reason of existence is integration with tests.

**Comment by wujuu** [comment]
> Maybe I will globally disable plotting in tests - it would be better than flag that the only reason of existence is integration with tests.

Ok
