### ISSUE TITLE
Document behavior for QA

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/recommender-system#33]
Document recommender's behavior for others to be able to understand how it should work (in a manner which does not require in-depth understanding of the RL workings).

The documentation should be usable as a reference and introduction to the system in the future, as well as for the QA side of the team, to be able to prepare test cases and quality assurance scenarios.

**Comment by JanKapala** [comment]
Recommender's behaviour description (**I iteration**): https://docs.cyfronet.pl/display/FID/Recommender+System+behaviour+description

**Comment by JanKapala** [comment]
# Recommender's behaviour description (II iteration)
After consulatations with @roksanaer documentation has been splited into two versions:

- [for developers](https://docs.cyfronet.pl/x/uoBZBQ)
- [for external world](https://docs.cyfronet.pl/x/vINZBQ) (scientists, project managers, etc.)
