### ISSUE TITLE
Trainings recommendations - dumping mechanism

### ISSUE THREAD

**Issue by JanKapala** [cyfronet-fid/recommender-system#387]
1. Implement dump sending on the [Search Service](https://github.com/cyfronet-fid/eosc-search-service) side
2. Implement dump receiving and saving appropriate models to the DB (based on [schema](https://docs.google.com/spreadsheets/d/1YzXt1PDbkhRzH0iC1umOqK0yda03W-w-/edit#gid=481018847)) on the recommender side

Al of this should be based on existing dumping mechanism for Marketplace services

**Comment by Michal-Kolomanski** [comment]
It was decided to abort this feature
