### ISSUE TITLE
Recommendations API adjustments II

### ISSUE THREAD

**Issue by danielkryska** [cyfronet-fid/recommender-system#39]
Tested in two ways:
-   in normal chrome window after cookies cleaning
-   in separate chrome incognito windows
# Bugs
### ~~Redundant unique_id~~
-   **Description**: Unique_id of the logged in user is not empty. 
-   **Expected behaviour**: following API documentation: “unique_id - the unique identifier of the not logged user. Specified only if logged_user=False”.
-   **Steps to reproduce**: for the logged user:
	1.  Click recommended service name in the recommendation panel
   
### Invalid source.visit_id and target_visit_id of the same user_action
-   **Description**: visit_ids and unique_id are identical again, moreover they all are also identical with visit_ids and unique_id of the previous user_action.
-   **Expected behaviour**: source.visit_id i target.visit_id of the same user_action should be different and they should be also different from unique_id. Each visit on the page should correspond to unique visit_id and user actions should have appropriate visit_id in their sources and targets, as described [here](https://docs.cyfronet.pl/display/FID/Session+gathering) and [here](https://github.com/cyfronet-fid/marketplace/pull/1866#pullrequestreview-616187649)
-   **Steps to reproduce**: for logged in user:
	1.   Click recommended service name in the recommendation panel
	2.   On the next page click service details

Example for two above bugs:
**Enqueued user_action 1 in MP:**

    **10:53:19 web.1 | [ActiveJob] Enqueued Probes::ProbesJob (Job ID: 1755fcab-a8a3-4eca-a84d-c3156b32cfca) to Sidekiq(probes) with arguments: "{\"timestamp\":\"2021-03-24T09:53:19.775Z\",\"source\":{\"visit_id\":1616798682,\"page_id\":\"/services\",\"root\":{\"type\":\"recommendation_panel\",\"service_id\":57,\"panel_id\":\"v1\"}},\"target\":{\"visit_id\":1616798682,\"page_id\":\"/services/elastic-cloud-compute-cluster-ec3?from_recommendation_panel=true\"},\"action\":{\"type\":\"A\",\"text\":\"Elastic Cloud Compute Clust...\",\"order\":false},\"logged_user\":true,\"user_id\":1825,\"unique_id\":1616798682}"**

**Enqueued user_action2 in MP:**

    **11:05:01 web.1 | [ActiveJob] Enqueued Probes::ProbesJob (Job ID: 349d2126-01b8-47f5-9924-956cddc944d8) to Sidekiq(probes) with arguments: "{\"timestamp\":\"2021-03-24T10:05:01.762Z\",\"source\":{\"visit_id\":1616798682,\"page_id\":\"/services/elastic-cloud-compute-cluster-ec3\",\"root\":{\"type\":\"other\"}},\"target\":{\"visit_id\":1616798682,\"page_id\":\"/services/elastic-cloud-compute-cluster-ec3/details\"},\"action\":{\"type\":\"A\",\"text\":\"Details\",\"order\":false},\"logged_user\":true,\"user_id\":1825,\"unique_id\":1616798682}"**

### Not related visit_ids make user_actions chaining impossible
-   **Description**: visit_ids of consecutive user_actions are not related
-   **Expected behaviour**: In user journey, two consecutive user actions (for example clicking recommended service and then clicking its details) should obey: user_action1.target.visit_id == user_action2.source.visit_id. They should can be chained into consistent user journey as described [here](https://docs.cyfronet.pl/display/FID/Session+gathering) and [here](https://github.com/cyfronet-fid/marketplace/pull/1866#pullrequestreview-616187649)
-   **Steps to reproduce**: for anonymous user:
	1. Click recommended service name in the recommendation panel
	2. On the next page click service details

Example for above bug:
**Enqueued user_action1 in MP:**

    **11:11:20 web.1 | [ActiveJob] Enqueued Probes::ProbesJob (Job ID: 59903b4c-6ef7-436b-b681-ae33a94a1640) to Sidekiq(probes) with arguments: "{\"timestamp\":\"2021-03-24T10:11:20.117Z\",\"source\":{\"visit_id\":6380701618197596270,\"page_id\":\"/services\",\"root\":{\"type\":\"recommendation_panel\",\"service_id\":364,\"panel_id\":\"v2\"}},\"target\":{\"visit_id\":6380701618197596411,\"page_id\":\"/services/gbif-spain-collections-registry?from_recommendation_panel=true\"},\"action\":{\"type\":\"A\",\"text\":\"GBIF Spain Collections Registry\",\"order\":false},\"logged_user\":false,\"unique_id\":1616916152}"**

**Enqueued user_action2 in MP:**

    **11:12:54 web.1 | [ActiveJob] Enqueued Probes::ProbesJob (Job ID: f6102473-0658-4f49-980a-3b1715032125) to Sidekiq(probes) with arguments: "{\"timestamp\":\"2021-03-24T10:12:54.631Z\",\"source\":{\"visit_id\":6380701618197690784,\"page_id\":\"/services/gbif-spain-collections-registry\",\"root\":{\"type\":\"other\"}},\"target\":{\"visit_id\":6380701618197691003,\"page_id\":\"/services/gbif-spain-collections-registry/details\"},\"action\":{\"type\":\"A\",\"text\":\"Details\",\"order\":false},\"logged_user\":false,\"unique_id\":1616916152}"**

**Comment by danielkryska** [comment]
Both `Invalid source.visit_id and target_visit_id of the same user_action` and `Not related visit_ids make user_actions chaining impossible` are related to enhancement.

target of previous page should be source of next one.

**Comment by JanKapala** [comment]
No @danielkryska it's not enhencement, it's core feature bug.

**Comment by danielkryska** [comment]
Ticket will be continued in https://github.com/cyfronet-fid/recommender-system/issues/45
