### ISSUE TITLE
Unify Recommender's /recommendations endpoint for the sake of integration

### ISSUE THREAD

**Issue by Michal-Kolomanski** [cyfronet-fid/recommender-system#395]
There is a need to unify our **/recommendations** endpoint in order to be able to successfully integrate our Recommender with Recommender from Poznań. 

There are not a lot of changes needed to be done, but here is the specification: https://wiki.eoscfuture.eu/display/EOSCF/RS+facade
In the end, our API should look like this.

Required adjustments: 
- migration which will rename our **elastic_services** to **candidates**
- next adjustments are in what exactly we return. Currently, we return only a list of recommended services IDs, but the desired way will be to return:
![image](https://user-images.githubusercontent.com/47147210/186461125-9d12af81-d88c-4688-83c0-8668e7e5f447.png)
  - panel_id - the same as panel_id in the recommendation context (actually this one seems to be useless in our case, so it shouldn't be implemented)
  - recommendations - what we return on daily basis,
  - explanations and explanations_short - I know that this one is really hard to do in such a way that it would be meaningful, but our colleagues from Poznań are returning just simple explanation strings. 
  That is what they are using: 
"Publications similar to service previously ordered by you." 
"Previously you ordered a similar service." 
"Data sets that were visited by users who ordered similar services."
Could we do something similar? Or do you have a better idea? Please feel free to suggest a solution. Please also note that **explanations_short** should be short :)
  - score - we should also return the score of each recommendation - we will be at the same point merging our recommendations with those from Poznań so we need some scores to compare. 
  - return engine version in the response because sometimes recommendation engine used for response generation can be different than requested

**Comment by JanKapala** [comment]
"pannel_name" -> "panel_id", "score" -> "scores"
