### ISSUE TITLE
Remove logged_user parameter from /user_actions POST body update

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/recommender-system#43]
Api should be updated as follows:

1. `logged_user` should be removed from the parameters list
2. `user_id` should be optional (should remain as is)
3. `unique_id` should be always required

The logic underneath should work as follows:

_If `user_id` is set then we have logged_user otherwise user is anonymous_

**Comment by JanKapala** [comment]
The same filed is also in /recommendations POST body, I will apply same changes there. @michal-szostak could you confirm?
